using System.Web;
using System.Web.Optimization;

namespace MultisiteConstructionCompany
{
    public class BundleConfig
    {
        // For more information on bundling, visit http://go.microsoft.com/fwlink/?LinkId=301862
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                        "~/Scripts/jquery-{version}.js"));

            bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"));

            // Use the development version of Modernizr to develop with and learn from. Then, when you're
            // ready for production, use the build tool at http://modernizr.com to pick only the tests you need.
            bundles.Add(new ScriptBundle("~/bundles/modernizr").Include(
                        "~/Scripts/modernizr-*"));

            bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(
                      "~/Scripts/bootstrap.js",
                      "~/Scripts/respond.js"));

            bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/site.css"));

            bundles.Add(new StyleBundle("~/bundles/Template1").Include(
                "~/Template/fickle.aimmate.com/assets/css/bootstrap.min.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/bootstrap-progressbar-3.1.1.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/jquery-jvectormap.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/jquery.amaran.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/all-themes.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/awesome.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/default.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/blur.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/user.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/rounded.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/readmore.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/amaranjs/theme/metro.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/c3.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/calendario/ls-calendario.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/fullcalendar/fullcalendar.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/fullcalendar/fullcalendar.print.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/humane_themes/bigbox.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/humane_themes/jackedup.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/humane_themes/libnotify.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/icheck/skins/all.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/rangeSlider/ion.rangeSlider.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/rangeSlider/ion.rangeSlider.skinFlat.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/accordion.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/bootstrap-magnify.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/bootstrap-switch.min.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/cropper.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/custom_smart_wizard.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/dndTable.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/drag_drop_image.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/easyTree.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/fileinput.min.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/fluidbox.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/jplayer.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/jquery.datetimepicker.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/jquery.minicolors.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/jquery.remodal.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/jquery.toolbars.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/ladda-themeless.min.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/lightGallery.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/shuffle.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/simpleWeather.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/summernote.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/tab.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/TimeCircles.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/tsort.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/weatherFeed.css",
                "~/Template/fickle.aimmate.com/assets/css/style.css",
                "~/Template/fickle.aimmate.com/assets/css/responsive.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/validationEngine.jquery.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/bootstrapValidator.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/pace.css",
                "~/Template/fickle.aimmate.com/assets/css/plugins/selectize.bootstrap3.css"));

            bundles.Add(new ScriptBundle("~/bundles/Template2").Include(
                "~/Template/ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js",
                "~/Template/ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js",
                "~/Template/fickle.aimmate.com/assets/js/color.js",
                "~/Template/fickle.aimmate.com/assets/js/lib/jquery-1.11.min.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap.min.js",
                "~/Template/fickle.aimmate.com/assets/js/multipleAccordion.js",
                "~/Template/fickle.aimmate.com/assets/js/lib/jquery.easing.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.nanoscroller.min.js",
                "~/Template/fickle.aimmate.com/assets/js/switchery.min.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap-switch.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.easypiechart.min.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap-progressbar.min.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/flot/jquery.flot.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/flot/jquery.flot.pie.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/flot/jquery.flot.resize.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/layout.js",
                "~/Template/fickle.aimmate.com/assets/js/countUp.min.js",
                "~/Template/fickle.aimmate.com/assets/js/skycons.js",
                "~/Template/fickle.aimmate.com/assets/js/jvectormap/jquery-jvectormap-1.2.2.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jvectormap/jquery-jvectormap-world-mill-en.js",
                "~/Template/fickle.aimmate.com/assets/js/jvectormap/jquery-jvectormap-au-mill-en.js",
                "~/Template/fickle.aimmate.com/assets/js/jvectormap/jquery-jvectormap-uk-mill-en.js",
                "~/Template/fickle.aimmate.com/assets/js/jvectormap/jquery-jvectormap-us-mill-en.js",
                "~/Template/fickle.aimmate.com/assets/js/jvectormap/mall-map.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.amaran.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/dashboard.js",
                "~/Template/fickle.aimmate.com/assets/js/validationEngine/languages/jquery.validationEngine-en.js",
                "~/Template/fickle.aimmate.com/assets/js/validationEngine/jquery.validationEngine.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrapvalidator/bootstrapValidator.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/formValidation.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.maskedinput.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.autosize.js",
                "~/Template/fickle.aimmate.com/assets/js/pace.min.js",
                "~/Template/fickle.aimmate.com/assets/js/lib/jquery-2.1.1.min.js",
                "~/Template/fickle.aimmate.com/assets/js/lib/jqueryui.js",
                "~/Template/fickle.aimmate.com/assets/js/lib/modernizr.custom.js",
                "~/Template/fickle.aimmate.com/assets/js/lib/modernizr.js",
                "~/Template/fickle.aimmate.com/assets/js/selectize.min.js",
                "~/Template/fickle.aimmate.com/assets/js/c3js/c3js.min.js",
                "~/Template/fickle.aimmate.com/assets/js/c3js/d3.v3.min.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/jquery.sparkline.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/morris.min.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/raphael-min.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/chartjs/chart.min.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/flot/jquery.flot.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/flot/jquery.flot.pie.js",
                "~/Template/fickle.aimmate.com/assets/js/chart/flot/jquery.flot.resize.js",
                "~/Template/fickle.aimmate.com/assets/js/editable-table/jquery.dataTables.editable.js",
                "~/Template/fickle.aimmate.com/assets/js/editable-table/jquery.dataTables.js",
                "~/Template/fickle.aimmate.com/assets/js/editable-table/jquery.jeditable.js",
                "~/Template/fickle.aimmate.com/assets/js/editable-table/jquery.validate.js",
                "~/Template/fickle.aimmate.com/assets/js/gallery/evenheights.js",
                "~/Template/fickle.aimmate.com/assets/js/gallery/page.js",
                "~/Template/fickle.aimmate.com/assets/js/gallery/prism.js",
                "~/Template/fickle.aimmate.com/assets/js/gallery/shuffle.js",
                "~/Template/fickle.aimmate.com/assets/js/loader/ladda.js",
                "~/Template/fickle.aimmate.com/assets/js/loader/spin.js",
                "~/Template/fickle.aimmate.com/assets/js/media-player/jplayer.playlist.min.js",
                "~/Template/fickle.aimmate.com/assets/js/media-player/jquery.jplayer.inspector.js",
                "~/Template/fickle.aimmate.com/assets/js/media-player/jquery.jplayer.min.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/buttonSwitch.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/c3.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/calender.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/chartjs.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/checkboxRadio.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/comingSoon.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/composMail.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.flotchart.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.gallery.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.magnify.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.morris.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.profile.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.sparkline.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.timeline.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/demo.treeView.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/dragAndDrop.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/editor.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/fontAwesome.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/formWizard.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/glyphicons.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/googleMap.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/imageCrop.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/knobSlider.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/lockScreen.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/login.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/mail.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/media.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/noteTask.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/notification.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/pickerTool.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/registration.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/sampleForm.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/selectTag.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/table.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/uiElements.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/vectorMap.js",
                "~/Template/fickle.aimmate.com/assets/js/pages/widget.js",
                "~/Template/fickle.aimmate.com/assets/js/bootbox.min.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap-magnify.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap-progressbar.min.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap-rating-input.min.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap-switch.js",
                "~/Template/fickle.aimmate.com/assets/js/bootstrap-switch.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.autosize.js",
                "~/Template/fickle.aimmate.com/assets/js/cropper.js",
                "~/Template/fickle.aimmate.com/assets/js/data.js",
                "~/Template/fickle.aimmate.com/assets/js/easyTree.js",
                "~/Template/fickle.aimmate.com/assets/js/fileinput.min.js",
                "~/Template/fickle.aimmate.com/assets/js/fullcalender.min.js",
                "~/Template/fickle.aimmate.com/assets/js/humane.min.js",
                "~/Template/fickle.aimmate.com/assets/js/icheck.min.js",
                "~/Template/fickle.aimmate.com/assets/js/ion.rangeSlider.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.calendario.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.circliful.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.datetimepicker.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.dragtable.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.easypiecchart.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.fluidbox.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.gomap-1.3.2.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.knob.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.minicolors.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.nanoscroller.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.qrcode.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.remodal.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.simpleWeather.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.smartWizard.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.tablednd.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.toolbar.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery.zweatherfeed.min.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery-image-upload.js",
                "~/Template/fickle.aimmate.com/assets/js/jquery-sortable.js",
                "~/Template/fickle.aimmate.com/assets/js/lightGallery.js",
                "~/Template/fickle.aimmate.com/assets/js/markerclusterer.js",
                "~/Template/fickle.aimmate.com/assets/js/masonry.min.js",
                "~/Template/fickle.aimmate.com/assets/js/notify.min.js",
                "~/Template/fickle.aimmate.com/assets/js/pace.min.js",
                "~/Template/fickle.aimmate.com/assets/js/qrcode.js",
                "~/Template/fickle.aimmate.com/assets/js/selectize.min.js",
                "~/Template/fickle.aimmate.com/assets/js/shine.min.js",
                "~/Template/fickle.aimmate.com/assets/js/slip.js",
                "~/Template/fickle.aimmate.com/assets/js/summernote.min.js",
                "~/Template/fickle.aimmate.com/assets/js/tabulous.js",
                "~/Template/fickle.aimmate.com/assets/js/TimeCircles.js",
                "~/Template/fickle.aimmate.com/assets/js/tsort.js"));
        }
    }
}

